### ISSUE TITLE
Missing labels in plot graph

### ISSUE THREAD

**Issue by kriben** [atlefren/pitilt-frontend#1]
x label is time, y label could be temperature or gravity.

**Comment by kriben** [comment]
Support for better labels seems to be coming in recharts 1.0: 
https://github.com/recharts/recharts/issues/522

**Comment by atlefren** [comment]
Labels, and tics with units added. 

![image](https://user-images.githubusercontent.com/1829927/27225249-a8ca669c-5299-11e7-911c-6bd49da1664a.png)

**Comment by atlefren** [comment]
I interpret the lack of response as an approval ;)
