### ISSUE TITLE
Predefined filter on plots

### ISSUE THREAD

**Issue by kriben** [atlefren/pitilt-frontend#3]
It would be nice to be able to zoom in on the plot, and see the measurements for the last hour, last 12 hours, last 24 hours and last week.

**Comment by atlefren** [comment]
logic for "Last Day", "last week" , and "all" implemented, waiting for https://github.com/atlefren/pitilt-api/issues/12 to be implemented before this works.

Should be simple to revise and use "last hour", "last 12 hours" and "last 24 hours" if nedded. Not sure what is best, though

**Comment by atlefren** [comment]
closed
