### ISSUE TITLE
"Last week" filter contains data for only the last day on Mondays

### ISSUE THREAD

**Issue by kriben** [atlefren/pitilt-frontend#4]
Steps to reproduce:
1. Create a plot with data over multiple days in same week on a Monday.
2. Select the "Last week" view in the plot.

Expected results:
Should show aggregate values for last 7 days.

Actual results:
Shows aggregate values for since the beginning of the week.

**Comment by kriben** [comment]
The "Last day" has similar issues: it shows data only since 00:00. Renaming "Last week" to "Last 7 days" and "Last day" to "Last 24 hours", and displaying the corresponding data would be better.

**Comment by atlefren** [comment]
Closed in https://github.com/atlefren/pitilt-frontend/commit/4903f41649632dac69f107f7dd790feef04bf4d9
